services:
  localai:
    container_name: localai
    #image: localai/localai:latest-gpu-vulkan
    image: localai/localai:latest-aio-gpu-vulkan
    #shm_size: '8gb'
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - ./backends:/backends:z
      - ./models:/models:z
    ports:
      - 8080:8080

