FROM node:trixie

# Install Software
RUN apt-get update; apt-get install -y ansible curl git python3 pip gcc g++ gdb valgrind cmake rust-all

# certs
COPY certs/ /usr/local/share/ca-certificates/
RUN update-ca-certificates
